version: "3.8"
services:
    web:
        image: trafex/php-nginx
        deploy:
            replicas: 5
        ports:
            - 8080:8080
        volumes:
            - "/home/vagrant/bgapp/web:/var/www/html:ro"
        networks:
            - app-network
    db:
        image: amashofdna/bgapp-db
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: "12345"
networks:
    app-network:
